title: 24/7 discord bot Huff
description: dont
template:
  repo: 247-discord-bot-huff-template
  name: 247-discord-bot-huff
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
